# compose.yaml
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shlink_ui_rails_development
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    environment:
      - REDIS_URL=redis://redis:6379/0

  css:
    build: .
    command: bin/rails tailwindcss:watch
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    tty: true

  jobs:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: ./bin/jobs
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    tty: true
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - RAILS_LOG_LEVEL=debug
      - SOLID_QUEUE_LOG_LEVEL=debug
      - VERBOSE=true

volumes:
  dbdata:
  bundle:
  redis_data:
