# compose.yaml
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shlink_ui_rails_development
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true

  css:
    build: .
    command: bin/rails tailwindcss:watch
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    tty: true

volumes:
  dbdata:
  bundle:
