default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 1
      processes: 1

development:
  <<: *default
  dispatchers:
    - polling_interval: 2
      batch_size: 50
  workers:
    - queues: "*"
      threads: 2
      processes: 2
      polling_interval: 2

test:
  <<: *default

production:
  <<: *default
  workers:
    - queues: "*"
      threads: 3
      processes: 2